version: 0.0.{build}
os: Windows Server 2012 R2
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: T0CN6Rhd2CAhg368vxiH+RHgJgRzce4xmPu9lH6huFVq3/B58CG1Jl6bOxxk6CI6
before_build:
  - nuget restore ".\Moya.sln"
build:
  project: .\Moya.sln
  verbosity: minimal
test_script:
- ps: >-
    echo "test script"