version: 0.0.{build}
os: Windows Server 2012 R2
configuration: Release
environment:
  COVERALLS_REPO_TOKEN:
    secure: T0CN6Rhd2CAhg368vxiH+RHgJgRzce4xmPu9lH6huFVq3/B58CG1Jl6bOxxk6CI6
before_build:
  - nuget restore ".\src\Moya.sln"
  - nuget install ".\src\.nuget\packages.config" -OutputDirectory src\packages
build:
  project: .\src\Moya.sln
  verbosity: minimal
test_script:
- ps: >-
    $testFiles = @(
        "src/TestMoya/bin/Release/TestMoya.dll"
    )

    $xUnitAdapterPath = ".\src\packages\xunit.runner.visualstudio.2.0.1\build\_common\"

    $VsTestExecutable = "${Env:ProgramFiles(x86)}\Microsoft Visual Studio 12.0\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe"

    Remove-Item -Force -Recurse .\TestResults -ErrorAction SilentlyContinue

    & $VsTestExecutable /inIsolation /Enablecodecoverage /TestAdapterPath:"$xUnitAdapterPath" $testFiles /Settings:CodeCoverage.runsettings

    $coverageFilePath = Resolve-Path -path "src\TestResults\*\*.coverage"

    Remove-Item .\src\MoyaCoverage.coveragexml -ErrorAction SilentlyContinue

    $CodeCoverageExecutable ="${Env:ProgramFiles(x86)}\Microsoft Visual Studio 12.0\Team Tools\Dynamic Code Coverage Tools\CodeCoverage.exe"

    & $CodeCoverageExecutable analyze /output:MoyaCoverage.coveragexml "$coverageFilePath"
    
    Push-AppveyorArtifact MoyaCoverage.coveragexml

    $coverallsPath = Resolve-Path "src\packages\coveralls.net.*\tools\csmacnz.coveralls.exe"

    $coveralls = $coverallsPath.ToString()

    & $coveralls --dynamiccodecoverage `
                 -i MoyaCoverage.coveragexml `
                 --repoToken $env:COVERALLS_REPO_TOKEN `
                 --commitId $env:APPVEYOR_REPO_COMMIT `
                 --commitBranch $env:APPVEYOR_REPO_BRANCH `
                 --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR `
                 --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL `
                 --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE `
                 --jobId $env:APPVEYOR_JOB_ID `
                 --useRelativePaths `
                 -o coverage.json
                 
    Push-AppveyorArtifact coverage.json